PANDAS - SERIES 

In [1]:
import pandas as pd 

In [2]:
A = pd.Series(["ada", "roberta", 300 , "christain"], index=["a", "b", "c", "d"])

type(A)


pandas.Series

In [6]:
A.values


array(['ada', 'roberta', 300, 'christain'], dtype=object)

In [7]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [8]:
type(A.values)

numpy.ndarray

In [9]:
type(A.index)

pandas.Index

In [15]:
B = pd.Series(["ada", "roberta", 300 , "christain"], index=["a", "b", "c", "d"])

In [12]:
B["a"]

'ada'

In [17]:
B["a" : "c"]

a        ada
b    roberta
c        300
dtype: object

In [19]:
grades_dict = {"A":20, "A-": 15, "B": 10}
C = pd.Series(grades_dict)
type(C)

pandas.Series

In [22]:
C.index

Index(['A', 'A-', 'B'], dtype='str')

In [23]:
C.values    

array([20, 15, 10])

In [24]:
C.values

array([20, 15, 10])

In [26]:
mark_dict = {"A":20, "A-": 15, "B": 10, "C": 5}

mark = pd.Series(mark_dict)
mark 

A     20
A-    15
B     10
C      5
dtype: int64

In [27]:
mark.index

Index(['A', 'A-', 'B', 'C'], dtype='str')

In [28]:
mark.values

array([20, 15, 10,  5])

In [29]:
mark["A": "B"]

A     20
A-    15
B     10
dtype: int64

In [30]:
mark["A"]

np.int64(20)

In [31]:
mark[0:2]

A     20
A-    15
dtype: int64

PANDA DATAFRAMES 

In [33]:
grades_dict = {"A":20, "A-": 15, "B": 10}
mark_dict = {"A":20, "A-": 15, "B": 10, "C": 5}

grades = pd.Series(grades_dict) #this is a series
mark = pd.Series(mark_dict) #this is a series

In [37]:
D = pd.DataFrame({"Grades": grades, "Marks": mark})
D 
# NaN - means None 

,Grades,Marks
A,20.0,20
A-,15.0,15
B,10.0,10
C,NaN,5


In [38]:
grades_dict = {"A":20, "A-": 15, "B": 10}
mark_dict = {"C":20, "C-": 15, "D": 10}
grades = pd.Series(grades_dict) #this is a series
mark = pd.Series(mark_dict) #this is a series

In [39]:
E = pd.DataFrame({"Marks" : mark, "Grades" : grades})
E

,Marks,Grades
A,NaN,20.0
A-,NaN,15.0
B,NaN,10.0
C,20.0,NaN
C-,15.0,NaN
D,10.0,NaN


In [40]:
E.T

,A,A-,B,C,C-,D
Marks,NaN,NaN,NaN,20.0,15.0,10.0
Grades,20.0,15.0,10.0,NaN,NaN,NaN


In [41]:
E.index

Index(['A', 'A-', 'B', 'C', 'C-', 'D'], dtype='str')

In [42]:
E.values

array([[nan, 20.],
       [nan, 15.],
       [nan, 10.],
       [20., nan],
       [15., nan],
       [10., nan]])

In [43]:
grades_dict = {"A":20, "A-": 15, "B": 10}
mark_dict = {"A":20, "A-": 15, "B": 10}
grades = pd.Series(grades_dict) #this is a series
mark = pd.Series(mark_dict) #this is a series

F = pd.DataFrame({"Marks" : mark, "Grades" : grades})
F

,Marks,Grades
A,20,20
A-,15,15
B,10,10


ACCESSING ELEMENTS IN A PANDA DATAFRAMES 

In [44]:
F.values[2,0]

np.int64(10)

In [45]:
F.values[1,1]

np.int64(15)

In [46]:
F.values[2,1]

np.int64(10)

In [52]:
F = pd.DataFrame({"Marks" : mark, "Grades" : grades})
F

,Marks,Grades
A,20,20
A-,15,15
B,10,10


In [48]:
F.columns

Index(['Marks', 'Grades'], dtype='str')

In [50]:
F.index 

Index(['A', 'A-', 'B'], dtype='str')

In [51]:
F.values

array([[20, 20],
       [15, 15],
       [10, 10]])

In [56]:
Total_dict = {"A": 100, "A-": 50, "B": 70}
Total_dict

{'A': 100, 'A-': 50, 'B': 70}

Adding a column(dict) to a dataframe 

In [57]:
F["Total"] = Total_dict

In [58]:
F

,Marks,Grades,Total
A,20,20,100
A-,15,15,50
B,10,10,70


Performing basic operations with existing columns while adding the result as a column to the dataframe

In [61]:
F["Average"] = (F["Marks"] + F["Grades"]) / 2

In [62]:
F

,Marks,Grades,Total,Average
A,20,20,100,20.0
A-,15,15,50,15.0
B,10,10,70,10.0


Deleting a column from a dataframe 

In [64]:
F["diff"] = (F["Total"] - F["Grades"])
F

,Marks,Grades,Total,Average,diff
A,20,20,100,20.0,80
A-,15,15,50,15.0,35
B,10,10,70,10.0,60


In [65]:
F.pop("diff")


A     80
A-    35
B     60
Name: diff, dtype: int64

In [66]:
F

,Marks,Grades,Total,Average
A,20,20,100,20.0
A-,15,15,50,15.0
B,10,10,70,10.0


In [72]:
del F["Average"]


In [71]:
F

,Marks,Grades,Total
A,20,20,100
A-,15,15,50
B,10,10,70


In [73]:
G = F[F["Marks"]> 10]
G 

,Marks,Grades,Total
A,20,20,100
A-,15,15,50


In [74]:
H = F[F["Grades"]> 10]
H

,Marks,Grades,Total
A,20,20,100
A-,15,15,50


NaN - replacing NaN 

In [75]:
I_dict = {"B": "boy", "C": "cat", "D": "dog"}
j_dict = {"C": "cat", "D": "dog", "F": "french"}

I = pd.Series(I_dict)
J = pd.Series(j_dict)

k = pd.DataFrame({"I": I, "J": J})

In [76]:
k

,I,J
B,boy,NaN
C,cat,cat
D,dog,dog
F,NaN,french


In [84]:
L = k.fillna(10)
L

,I,J
B,boy,10
C,cat,cat
D,dog,dog
F,10,french


In [81]:
L

,I,J
B,boy,0
C,cat,cat
D,dog,dog
F,0,french


Explicit and Implicit index in panda 